name: flake8 Lint

on: [pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4 # v4.2.2
      - name: Set up Python environment
        uses: actions/setup-python@v5 # v5.4.0
        with:
          python-version: "3.11"
      # Install specific flake8 version (this step is not required. Default is "latest").
      - run: pip install flake8
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3 # v3.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review  # or github-check for GitHub Checks UI
          filter_mode: nofilter
          fail_level: any